### ISSUE TITLE
Carousel cannot handles dynamic children.

### ISSUE THREAD

**Issue by minel** [Trendyol/react-carousel#10]
I've used Carousel comp. with dynamic=true parameter but it can't handle dynamic children when i want to use it on pagination.

**Comment by hasangenc0** [comment]
you should set dynamic={true} prop to listen for state changes, but it cannot handle pagination.
Pagination feature #11 is now beta in version [1.0.7-beta.3](https://www.npmjs.com/package/@trendyol-js/react-carousel/v/1.0.7-beta.3)
