### ISSUE TITLE
Swiping not working

### ISSUE THREAD

**Issue by wantToHawaii** [Trendyol/react-carousel#15]
**Actual behaviour:**
Use `Carousel` element with `swiping={true}` property.
Try to swipe - swiping not working.

**Expected behaviour:**
Swiping is working.

Live example on [codesandbox](https://codesandbox.io/s/trendyol-jsreact-carousel-peaceful-rosalind-g8pbq-g8pbq)

**Comment by hasangenc0** [comment]
You should add `swipeOn` property in this case, because your carousel showing 1 item per page. `swipeOn`  defines the 
percentage of swipe amount according to the 1 item width to trigger swipe effect.

example code:
```jsx
import { Carousel } from "@trendyol-js/react-carousel";

export default function App() {
  return (
    <div className="App">
      <Carousel swiping swipeOn={0.1}>
        <div>1</div>
        <div>2</div>
        <div>3</div>
        <div>4</div>
      </Carousel>
    </div>
  );
}
```

@wantToHawaii
