### ISSUE TITLE
setInterval 

### ISSUE THREAD

**Issue by AntonioLourencos** [Trendyol/react-carousel#41]
Hello, I looked in the Documentation about the interval, for the Carousel to move, but unfortunately don't have it.
It's posible I create it and increment on my code?

**Comment by hasangenc0** [comment]
Hi @AntonioLourencos,
Unfortunately, this library doesn't have an auto-slide feature. But PRs are welcome.

By the way, I think a work-around is possible:
````js
setInterval(() => {
 document.querySelector('[data-direction=right]').click();
}, 2000);
````
