### ISSUE TITLE
Buttons always are visible in the RTL layout

### ISSUE THREAD

**Issue by hadimostafapour** [Trendyol/react-carousel#42]
I'm using Scrolling Carousel to achieve something like your [example](https://trendyol.github.io/react-carousel/docs/scrolling-carousel).

Everything works fine, but when the carousel reaches the end, both buttons stay visible.

In addition, this works fine on the LTR layout but breaks in the RTL layout.

**Comment by hasangenc0** [comment]
Hi @hadimostafapour,
To be honest, I never tested this library in RTL content. I will investigate this in my available time. It would be awesome if you provide minimal reproduction.
