### ISSUE TITLE
Arrow button not rendering correctly

### ISSUE THREAD

**Issue by Nishant-Pall** [Trendyol/react-carousel#43]
I'm using the library to create a slideshow, the navigation button is just a simple HTML button and doesn't have the styling such as shown in the docs. 
This is how I'm using the component
```
const SlideShow = () => (
  <Carousel className="carousel" slide={1} show={1} infinite={false} responsive={true}>
    {array.map(slide => (
      <div className="carousel-item">
        <h1>{slide.title}</h1>
        <ul>
          <li>1</li>
          <li>1</li>
          <li>1</li>
        </ul>
      </div>
    ))}
  </Carousel>
);
export default SlideShow;
```

Do I need to style the buttons myself? or is there an issue with how I'm using the library

**Comment by hasangenc0** [comment]
If you don't use custom arrow props like `rightArrow` or `leftArrow` you should add some styles like this https://github.com/Trendyol/react-carousel/issues/12#issuecomment-784387672.

Or you can use your pre-styled custom arrows:
```jsx
<Carousel
	leftArrow={<CustomArrow/>}
	rightArrow={<CustomArrow/>}
/>
```
