### ISSUE TITLE
This package is not reponsive

### ISSUE THREAD

**Issue by udemezue01** [Trendyol/react-carousel#48]
I installed this package in my gatsby project, but when I wanted to make it responsive on mobile, I get errors, what, do I do about it

**Comment by sulaimanwebdev** [comment]
1. It's not responsive.
2.  It is not letting me add arrow icons

**Comment by hasangenc0** [comment]
You can see that `Carousel` works with different dimensions like below:

<img width="300" height="500" src="https://user-images.githubusercontent.com/26026780/135498662-352dde9d-e62e-4799-a909-bf788a26589b.png">

@udemezue01 can you create minimal reproduction of the issue that you are facing.

**Comment by hasangenc0** [comment]
@sulaimanwebdev you can pass custom arrows to both `Carousel` and `ScrollingCarousel`.
```jsx
<Carousel
	leftArrow={<CustomArrow/>}
	rightArrow={<CustomArrow/>}
/>
```

**Comment by udemezue01** [comment]
Here is a screenshot of the error occurred![Screenshot_20210930-180633_Chrome.jpg](https://user-images.githubusercontent.com/16034417/135499988-0a9bdd4a-abf4-4cee-b0ef-2e46caf0e862.jpg)

**Comment by udemezue01** [comment]
Can I display a certain slide based on the screenslide.

**Comment by sulaimanwebdev** [comment]
Is got a better option: React-Alice-Carousel
It has the code for responsive like this:

    const responsive = {
        0: { items: 1 },
        600: { items: 2 },
        837: { items: 3 },
        1024: { items: 4 },
    };

**Comment by sulaimanwebdev** [comment]
Ohh. I didn't knew that, I spent hours to put arrows. I think it should be on documentation also

**Comment by hasangenc0** [comment]
carousel arranges item's width according to the root container width and `show` prop.

**Comment by hasangenc0** [comment]
> Is got a better option: React-Alice-Carousel It has the code for responsive like this:
> 
> ```
> const responsive = {
>     0: { items: 1 },
>     600: { items: 2 },
>     837: { items: 3 },
>     1024: { items: 4 },
> };
> ```

I can add this feature for the next release. Until then you can do it programmatically by listening to window size and setting show prop according to that.

**Comment by sulaimanwebdev** [comment]
> > Is got a better option: React-Alice-Carousel It has the code for responsive like this:
> > ```
> > const responsive = {
> >     0: { items: 1 },
> >     600: { items: 2 },
> >     837: { items: 3 },
> >     1024: { items: 4 },
> > };
> > ```
> 
> I can add this feature for the next release. Until then you can do it programmatically by listening to window size and setting show prop according to that.

Yeah, that's great
