### ISSUE TITLE
Support React@17.0.2

### ISSUE THREAD

**Issue by ipr0310** [Trendyol/react-carousel#49]
Hi! this is a pretty awesome component!
But it seems that the library does not support React@17.x

![image](https://user-images.githubusercontent.com/35440957/135734423-2a2bdf9b-4433-4db9-92fc-17c335a006a9.png)

**Comment by Propo41** [comment]
same problem

**Comment by hasangenc0** [comment]
Hi @ipr0310,
This library is compatible with all react versions. The issue that you are facing occurs in some npm versions. 
Please try to update your npm version, if it does not solve the issue please let me know. (If you can not change your npm version pass `--legacy-peer-deps` to workaround.)

**Comment by moriko** [comment]
Hey @hasangenc0, this doesn't solve the issue on the newest npm version, unless the `legacy-peer-deps=true` line is added in the `.npmrc` file. Since the package is compatible with all react versions why not just remove the peer dependency?

**Comment by hasangenc0** [comment]
Hey @moriko , which npm version are you currently using? I tried `npm i @trendyol-js/react-carousel --legacy-peer-deps` on `8.11.0`  and it just worked fine.

**Comment by hasangenc0** [comment]
btw I'm going to solve this issue you won't need to use `--legacy-peer-deps` anymore. I will let you know when it's ready.

**Comment by hasangenc0** [comment]
it should be fixed now with version `3.0.0`

**Comment by moriko** [comment]
> Hey @moriko , which npm version are you currently using? I tried `npm i @trendyol-js/react-carousel --legacy-peer-deps` on `8.11.0` and it just worked fine.

Our deployment environment is using LTS Node (16.15.1) and the npm `8.11.0` and kept on throwing errors. There might be a bug on npm side, the only difference (before adding the --legacy-peer-deps) was in the package-json fil related to `"devOptional": true` vs `"dev": true` difference 🤷🏻‍♀️.

And thanks for the `3.0.0` version ✌🏻
