### ISSUE TITLE
Change transform property

### ISSUE THREAD

**Issue by nav11dd** [Trendyol/react-carousel#51]
Hi! Thanks for your awesome component!
I'm using `Carousel` component and I need to reset/change `transform` CSS property on `ItemProvider` component when I select another tab. How can I do it?

https://github.com/Trendyol/react-carousel/blob/8e4d576a262a8c3551b53d395b9888299be0d3bf/src/components/item/index.tsx#L100

Or how can I change styles for this element?

**Comment by hasangenc0** [comment]
You can not change the transform property because it depends on the animation state. 
If you want `Carousel` to show the first item after switching between tabs, you should re-render with new items.
