### ISSUE TITLE
Invalid attribute name: ``

### ISSUE THREAD

**Issue by IsmaelChoque** [Trendyol/react-carousel#54]
### Describe the bug

when I implement and use the component I get that warning

![Captura de pantalla de 2021-12-12 08-34-51](https://user-images.githubusercontent.com/60803299/145712508-d2c18adc-171e-4b92-9ae2-3bf3fac46e1a.png)

### Reproduction

Only this is my code

![Captura de pantalla de 2021-12-12 08-38-54](https://user-images.githubusercontent.com/60803299/145712662-6bb410a7-4e2e-4d83-9ede-fa0a2cb29df2.png)

### System Info

```shell
SO Ubuntu 21.10, Browser Chrome, Package Manager Yarn
```

### Used Package Manager

yarn

### Validations

- [ ] Follow our [Code of Conduct](https://github.com/Trendyol/react-carousel/blob/master/CODE_OF_CONDUCT.md)
- [ ] Read the [Contributing Guidelines](https://github.com/Trendyol/react-carousel/blob/master/CONTRIBUTING.md).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hasangenc0** [comment]
It seems to be working https://codesandbox.io/s/frosty-mahavira-vwkqq
are you sure if this is related to this package?

**Comment by IsmaelChoque** [comment]
Exact works, [https://codesandbox.io/s/frosty-mahavira-vwkqq](https://codesandbox.io/s/frosty-mahavira-vwkqq), but in your console the warning is still there

**Comment by murelain** [comment]
Just encountered the same error

**Comment by jamesonvparker** [comment]
This is driving me crazy at the moment.  I'm pretty sure it's causing a render problem.  Finally decided to check here and glad to see it's not just me.

**Comment by hasangenc0** [comment]
It's fixed in release [v2.0.1](https://github.com/Trendyol/react-carousel/releases/tag/v2.0.1)

**Comment by jamesonvparker** [comment]
Thank you @hasangenc0
