### ISSUE TITLE
sliderBase position is relative

### ISSUE THREAD

**Issue by doebling** [Trendyol/react-carousel#56]
### Describe the bug

Hello,

i can´t make my slidebar because the position of the sliderBase is relative. The carousel is over my slidebar.

![image](https://user-images.githubusercontent.com/88392704/147418213-b57d0dea-811b-4ca0-a6e4-fd77cf111c9c.png)

Why is the position relative and can you remove it please? :)

With best regards

### Reproduction

Just do a sidebar

### System Info

```shell
React, Typescript, react-carousel
```

### Used Package Manager

npm

### Logs

```shell
/
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/Trendyol/react-carousel/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Trendyol/react-carousel/blob/master/CONTRIBUTING.md).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hasangenc0** [comment]
The base wrapper should have `relative` position to locate items and buttons. It can't be changed.

If you want to remove it you can override the style by adding custom CSS.

**Comment by doebling** [comment]
How can i overwrite it?

**Comment by hasangenc0** [comment]
```jsx
<ScrollingCarousel className="customClass" />
```

```css
.customClass { position: absolute!important; }
```
