### ISSUE TITLE
Item re-renders on arrow press

### ISSUE THREAD

**Issue by dmitry-karpushyn** [Trendyol/react-carousel#57]
### Describe the bug

After clicking on the left / right arrow, all elements are re-rendering. This causes an issue, when you have some dynamic content inside

### Reproduction

1) Add some dynamic content to the item (video/music)
2) Press left/right arrow

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 4.97 GB / 15.89 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\frontend\node_modules\.bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.55)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @trendyol-js/react-carousel: ^2.0.1 => 2.0.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/Trendyol/react-carousel/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Trendyol/react-carousel/blob/master/CONTRIBUTING.md).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hasangenc0** [comment]
`Carousel` component needs to re-render sometimes (not always) to handle specific cases (infinite scroll etc.). But you can use `ScrollingCarousel` component with media elements such as `video` and `audio`.
