### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by stevenKirill** [Trendyol/react-carousel#58]
### Describe the bug

I want to make my carousel responsive in my next.js app but i got thw error window is not defined when i try to pass prop responsive={true}

### Reproduction

![carousel](https://user-images.githubusercontent.com/47239173/149658201-424b8a22-5fdf-46ab-b261-d55ef5457c54.png)
![carousel2](https://user-images.githubusercontent.com/47239173/149658204-ddfb2d73-a1f4-4f32-83f9-0ef03eca075d.png)

### System Info

```shell
Chrome last version
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/Trendyol/react-carousel/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Trendyol/react-carousel/blob/master/CONTRIBUTING.md).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hasangenc0** [comment]
if the error only occurs when `responsive` prop is `true`, you can workaround like down below:

```jsx
<Carousel responsive={typeof window !== "undefined"} />
```

if it's not, please provide me a minimal reproduction.

**Comment by stevenKirill** [comment]
No, I mean that I want to make it responsive if it's possible, Does prop responsive={true} can make my carousel responsive?

**Comment by hasangenc0** [comment]
The error you mentioned above occurs if you use server-side rendering, but it is not related to responsivity. If the `responsive` prop is true, it adjusts the all of child components' width according to the screen size dynamically.

**Comment by pavandeore** [comment]
keep the scrollable thing in  component directory remove it from pages and render it on pages with dynamic imports setting ssr: false  might work..

**Comment by stevenKirill** [comment]
Thanks everyone!
