### ISSUE TITLE
Lack of customizability on ScrollingCarousel

### ISSUE THREAD

**Issue by ghost** [Trendyol/react-carousel#59]
### Clear and concise description of the problem

The ScrollingCarousel component lacks a bunch of props which Carousel has, such as "show", "slide" etc. You also cannot modify/customize the arrows and such.
Currently if I try to use it, the children just squish together not even filling up the entire document width, the right arrow (it isn't even on the right, it's at the top of the children components) appears and dissapears as it feels and the "left" one is only there when it moves (scrolls).

### Suggested solution

Add customizability props to ScrollingCarousel.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/Trendyol/react-carousel/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Trendyol/react-carousel/blob/master/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hasangenc0** [comment]
If you need the show and slide properties you should use `Carousel` component. Also, you can modify the arrows in `ScrollingCarousel`.
It would be helpful for detecting issues that you are facing if you can provide a minimal reproduction repo.

**Comment by mihabozic123** [comment]
To clarify, I am using "dynamic" content, so it sort of re-renders my content, basically making it invisible for a couple seconds before it shows again. I saw [this comment](https://github.com/Trendyol/react-carousel/issues/57#issuecomment-1010265103) where you said:
> you can use `ScrollingCarousel` component with media elements

Maybe I misunderstood what you meant there, but how am I supposed to prevent my content from re-rendering (AND make it as customizable as `Carousel` is) otherwise?

**Comment by mihabozic123** [comment]
Would it be possible to modify the module and make it do what I want, or should I start looking for alternatives?

**Comment by hasangenc0** [comment]
You can do the customizations you mentioned using the `ScrollingCarousel`, except for the `slide` and `show` thing.
