### ISSUE TITLE
window is not defined when used the responsive props in the nextjs application

### ISSUE THREAD

**Issue by MuhammadMinhaj** [Trendyol/react-carousel#72]
### Describe the bug

I've tried to use the Carousel component in the NextJS application. Everything was fine before I used the `responsive`  props with the Carousel component. When I've passed responsive props then throwing the error. such - window is not defined

### Reproduction

There are two image links provided to see the error.
https://ibb.co/G0br5h8
https://ibb.co/hsYv7DZ

### System Info

```shell
Chrome Version 100.0.4896.75 (Official Build) (64-bit)
```

### Used Package Manager

yarn

### Logs

```shell
ReferenceError: window is not defined
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/Trendyol/react-carousel/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Trendyol/react-carousel/blob/master/CONTRIBUTING.md).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hasangenc0** [comment]
hi @MuhammadMinhaj , I think it is because of server-side rendering. It's a known issue but I didn't have time to fix that. I'm gonna release a fix for this asap.

**Comment by MuhammadMinhaj** [comment]
> hi @MuhammadMinhaj , I think it is because of server-side rendering. It's a known issue but I didn't have time to fix that. I'm gonna release a fix for this asap.

Okay brother

**Comment by hasangenc0** [comment]
@MuhammadMinhaj can you try this version `@trendyol-js/react-carousel@3.0.0-beta.4`

**Comment by MuhammadMinhaj** [comment]
@hasangenc0 Okay bro and thank you so much.
