### ISSUE TITLE
When click to an item, scroll until the element is fully visible in the viewport.

### ISSUE THREAD

**Issue by mmayadag** [Trendyol/react-carousel#75]
### Clear and concise description of the problem

When Any item clicked if item isn't fully inside current view slide item to current position than trigger click action

### Suggested solution

- [ ] Create a props for this feature
- [ ] Create a placeholder view and show that placeholder if item isn't current item.
- [ ] When you click that placeholder view. 
- [ ] Trigger Slide action to left or right
- [ ] Than trigger children's click action

### Validations

- [X] Follow our [Code of Conduct](https://github.com/Trendyol/react-carousel/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Trendyol/react-carousel/blob/master/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by isbarreix** [comment]
@hasangenc0 @mmayadag  what happened whit this feature?
