### ISSUE TITLE
Using infinite with images causes images to rerender with each slide

### ISSUE THREAD

**Issue by beppek** [Trendyol/react-carousel#80]
### Describe the bug

Using infinite slide with image items will cause the images to rerender each time you slide. 

It happens because the items array is changed with each slide in this function: https://github.com/Trendyol/react-carousel/blob/42f1e199185519783bd7073185a959661f03d341/src/helpers/index.ts#L141. 

The result is a flicker of all images in the slider as the src is reloaded.

### Reproduction

Use items with images.

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 135.95 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.7.2 - ~/.nvm/versions/node/v17.7.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v17.7.2/bin/yarn
    npm: 8.5.2 - ~/.nvm/versions/node/v17.7.2/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Edge: 99.0.1150.39
    Safari: 15.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/Trendyol/react-carousel/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Trendyol/react-carousel/blob/master/CONTRIBUTING.md).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hasangenc0** [comment]
It's probably because you have opened dev tools, if you uncheck disable cache, or close the devtools, it shouldn't happen.

**Comment by beppek** [comment]
Right, I definitely did that. Let me check if it fixes it.

**Comment by beppek** [comment]
Yep that did it, thanks! Closing this issue
