### ISSUE TITLE
 rightArrow and leftArrow prop not working for ScrollingCarousel

### ISSUE THREAD

**Issue by script8888** [Trendyol/react-carousel#81]
### Describe the bug

I tried using the RightArrow and Left Arrow prop for **ScrollingCarousel** component but it didn't work
It works fine with Carousel though.

This is the button that shows up:
<img width="286" alt="Capture" src="https://user-images.githubusercontent.com/52074770/168446295-f2c98d70-816e-4a99-a400-96695c69636a.PNG">

### Reproduction

https://codesandbox.io/s/frosty-firefly-l440tt?file=/src/App.js

### System Info

```shell
System:
    OS: Windows 10
    Memory: 8gb
  Binaries:
    Node: 16.13.4
    npm: 8.1.0
  Browsers:
    Chrome: 101.0.4951.67
  npmPackages:
    @trendyol-js/react-carousel: 2.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/Trendyol/react-carousel/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Trendyol/react-carousel/blob/master/CONTRIBUTING.md).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hasangenc0** [comment]
you can use `rightIcon` and/or `leftIcon` props to set custom buttons for `ScrollingCarousel`
```jsx
<ScrollingCarousel
      rightIcon={"right"}
      leftIcon={"left"}
    />
```
