### ISSUE TITLE
Carousel not responding

### ISSUE THREAD

**Issue by zeraphosa** [Trendyol/react-carousel#88]
### Describe the bug

I tried just an example like Readme.md usage section. But Carousel is not showing anything on screen.

Result with Carousel tag: [https://i.im.ge/2022/08/16/O2OnSS.1.png](url) - nothing
Result with when using div as a Carousel tag: [https://i.im.ge/2022/08/16/O2SAl6.2.png](url)

### Reproduction

[https://github.com/zeraphosa1/trendyol_carousel_example/tree/main](url)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 7.11 GB / 15.86 GB
  Binaries:
    Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (100.0.1185.36)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @trendyol-js/react-carousel: ^3.0.0 => 3.0.0
```

### Used Package Manager

npm

### Logs

```shell
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/Trendyol/react-carousel/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Trendyol/react-carousel/blob/master/CONTRIBUTING.md).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hasangenc0** [comment]
I tried your repo and it just worked as below:

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/26026780/184941298-d95227c4-19a2-4acd-8b1e-37d4a239d84f.png">

Can you share more details about your dev environment?

**Comment by zeraphosa** [comment]
[SOLVED] I tried npm link project/node_modules/@trendyol-js/react-carousel and then it worked.
